In [1]:
import numpy as np
import pandas as pd
import sys
import matplotlib.pyplot as plt
import seaborn as sns
import graphviz 
import os
import pickle
import sklearn
from sklearn.preprocessing import OneHotEncoder, StandardScaler, PowerTransformer, RobustScaler
from sklearn import datasets, linear_model, preprocessing, neighbors
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split,cross_val_score,GridSearchCV,KFold,RandomizedSearchCV,validation_curve
from sklearn.metrics import accuracy_score, confusion_matrix,mean_absolute_error,mean_squared_error, r2_score
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.svm import SVC
from sklearn.compose import make_column_selector as selector
from sklearn.compose import ColumnTransformer
import xgboost as xgb

In [26]:
df_oh = pd.read_csv('../台北市_predictset_onehot.csv', engine='python',index_col=[0])
df_oh

,交易年,總樓層數,主要建材,有無管理組織,車位總價元,建物移轉總面積坪,每坪價格,車位,屋齡,房間數,...,交易標的_房地(土地+建物),交易標的_房地(土地+建物)+車位,都市土地使用分區_住,都市土地使用分區_其他,都市土地使用分區_商,建物型態_住宅大樓(11層含以上有電梯),建物型態_公寓(5樓含以下無電梯),建物型態_套房(1房1廳1衛),建物型態_華廈(10層含以下有電梯),建物型態_透天厝
1,4,33,1,1,0.0,34.932700,64.695829,0,1,5,...,1,0,0,0,1,1,0,0,0,0
2,4,10,4,1,0.0,12.405525,48.365547,0,8,2,...,1,0,1,0,0,0,0,1,0,0
3,4,12,4,1,0.0,66.271700,44.061040,1,5,7,...,0,1,1,0,0,1,0,0,0,0
5,4,5,4,1,0.0,69.039575,50.695561,1,7,8,...,0,1,1,0,0,0,0,0,1,0
7,4,12,4,1,0.0,24.293775,50.218626,0,34,4,...,1,0,1,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
259317,9,27,1,0,440.0,85.301975,62.483899,2,0,9,...,0,1,1,0,0,1,0,0,0,0
259318,9,27,1,0,420.0,68.113925,57.844266,2,0,7,...,0,1,1,0,0,1,0,0,0,0
259319,9,27,1,0,220.0,58.430900,60.926667,1,0,7,...,0,1,1,0,0,1,0,0,0,0
259320,9,27,1,0,260.0,68.274250,66.935924,1,0,8,...,0,1,1,0,0,1,0,0,0,0
259323,9,8,4,0,0.0,21.973600,84.191939,0,0,5,...,1,0,1,0,0,0,0,0,1,0

In [27]:
X=df_oh.drop(columns=['每坪價格','車位'])
y=df_oh['每坪價格']

In [28]:
with open("model_XGBR_taipei.pickle", 'rb') as f:
        xgbr_load = pickle.load(f)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)
y_test_pred=xgbr_load.predict(X_test)

In [31]:
print(f'RMSE: {(mean_squared_error(y_test, y_test_pred,squared=False)):.3f}')
print(f'MAE:{(mean_absolute_error(y_test, y_test_pred)):.3f}')
print(f'R2:{(r2_score(y_test, y_test_pred)):.3f}')

RMSE: 10.179
MAE:7.167
R2:0.743